# Generated by Django 5.1.3 on 2025-01-31 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_author_options_alter_author_date_of_death"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookinstance",
            options={
                "ordering": ["due_back"],
                "permissions": (("can_view_book_instance", "Can view book instance"),),
            },
        ),
    ]
