# Generated by Django 5.1.3 on 2025-02-02 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_bookinstance_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={
                "ordering": ["last_name", "first_name"],
                "permissions": (
                    ("can_add_author", "Can add author"),
                    ("can_delete_author", "Can delete author"),
                    ("can_change_author", "Can change author"),
                ),
            },
        ),
    ]
